---
title: Koon Groupe
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  sliders:
    title: sliders
    output: true
email: contact@koon-group.com
description: "<p class=\"text-justify\">Le groupe Koon est une firme d’ingénierie
  spécialisée en électromécanique, bâtiments et travaux publics,ouvrages métalliques,froid
  et climatisation,infographie et informatique. </p>\n\t\t\t\t\t\t\t\t\t<p class=\"text-justify\">Chez
  Koon groupe l’écoute des besoins du client,l'excellence et l’intégrité sont les
  valeurs sur lesquelles s'appuient notre engagement. Notre priorité demeure la satisfaction
  de nos clients</p>\n\t\t\t\t\t\t\t\t\t<ul class=\"list-icons\">\n\t\t\t\t\t\t\t\t\t\t<li><i
  class=\"icon-check-1\"></i> La qualité des services rendus</li>\n\t\t\t\t\t\t\t\t\t\t<li><i
  class=\"icon-check-1\"></i> Un service direct et une intervention rapide</li>\n\t\t\t\t\t\t\t\t\t\t<li><i
  class=\"icon-check-1\"></i> Le respect des échéanciers</li>\n\t\t\t\t\t\t\t\t\t\t<li><i
  class=\"icon-check-1\"></i> Des honoraires compétitifs sur mesure</li>\n\t\t\t\t\t\t\t\t\t</ul>"
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
plugins:
- jekyll-feed
text: Le groupe KOON regroupe des professionnels et ingénieurs d'expérience ayant
  travaillé sur le conception, la réalisation et la coordination de beaucoup de projets,
  tout en respectant budgets et échéanciers.
tel: "+221 77 359 13 44"
adresse: Villa 117 Y, Hann Maristes 2 Dakar, Sénégal
